site:
  title: Tech Courses

content:
  sources:
    - url: .
      branches: main

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable

runtime:
  cache_dir: ./cache